"""Type stub for the native Rust extension `tyo3._native_impl`.

The native module is compiled via PyO3/maturin and exports:
- ``TyProject`` — the main project handle (a pyclass)
- ``TySnapshot`` — an immutable read-only project snapshot (a pyclass)
- ``TyHeadView`` — a floating warm view of the live HEAD (Phase 9)
- Exception types — Python-visible subclasses of PyRuntimeError

All return types are annotated as ``Any`` because the Rust layer returns
pythonize'd dicts that are validated into Pydantic models downstream.
"""

from typing import Any

class ProjectClosedError(RuntimeError): ...
class PathResolutionError(RuntimeError): ...
class PositionError(RuntimeError): ...

class TyProject:
    """A live handle to an open ty project database."""

    @staticmethod
    def open(root: str) -> TyProject: ...
    def reload(self) -> None: ...
    def close(self) -> None: ...
    @property
    def head(self) -> int: ...
    def snapshot(self, at: int | None = None) -> TySnapshot: ...
    def code_delta_full(self) -> Any: ...
    def edit(self, path: str, text: str) -> Any: ...
    def edit_many(self, edits: dict[str, str]) -> Any: ...
    def edit_virtual(self, uri: str, text: str) -> Any: ...
    def sync_path(self, path: str) -> Any: ...
    def discard(self, path: str) -> Any: ...
    def sync_all(self) -> Any: ...
    def watch(self) -> None: ...
    def unwatch(self) -> None: ...
    def flush_watch(self) -> None: ...
    def poll_changes(self) -> Any | None: ...
    def _inject_changes(self, changes: list[tuple[str, str]]) -> None: ...
    def head_view(self) -> TyHeadView: ...

class TySnapshot:
    """An immutable, revision-pinned read view of an open ty project database."""

    @property
    def revision(self) -> int: ...
    def files(self) -> list[str]: ...
    def code_delta_full(self) -> Any: ...
    def check(self) -> Any: ...
    def check_file(self, path: str) -> Any: ...
    def document_symbols(self, path: str) -> Any: ...
    def workspace_symbols(self, query: str) -> Any: ...
    def goto_definition(self, path: str, line: int, column: int) -> Any: ...
    def goto_declaration(self, path: str, line: int, column: int) -> Any: ...
    def goto_type_definition(self, path: str, line: int, column: int) -> Any: ...
    def find_references(self, path: str, line: int, column: int, include_declaration: bool) -> Any: ...
    def semantic_tokens(
        self,
        path: str,
        *,
        start_line: int | None = None,
        start_col: int | None = None,
        end_line: int | None = None,
        end_col: int | None = None,
    ) -> Any: ...
    def file_occurrences(self, path: str) -> Any: ...
    def type_hierarchy(self, path: str, line: int, column: int) -> Any: ...
    def class_supertypes(self, path: str, line: int, column: int) -> Any: ...
    def hover(self, path: str, line: int, column: int) -> Any: ...
    def document_highlights(self, path: str, line: int, column: int) -> Any: ...
    def can_rename(self, path: str, line: int, column: int) -> Any: ...
    def rename(self, path: str, line: int, column: int, new_name: str) -> Any: ...
    def selection_ranges(self, path: str, line: int, column: int) -> Any: ...
    def folding_ranges(self, path: str) -> Any: ...
    def signature_help(self, path: str, line: int, column: int) -> Any: ...
    def completions(self, path: str, line: int, column: int, *, auto_import: bool = True) -> Any: ...
    def inlay_hints(self, path: str) -> Any: ...
    def hints(self, path: str) -> Any: ...
    def code_actions(
        self,
        path: str,
        start_line: int,
        start_col: int,
        end_line: int,
        end_col: int,
        diagnostic_id: str,
    ) -> Any: ...
    def close(self) -> None: ...

class TyHeadView:
    """A floating, warm view of the live HEAD (cancel-retried reads)."""

    def files(self) -> list[str]: ...
    def check(self) -> Any: ...
    def check_file(self, path: str) -> Any: ...
    def document_symbols(self, path: str) -> Any: ...
    def workspace_symbols(self, query: str) -> Any: ...
    def goto_definition(self, path: str, line: int, column: int) -> Any: ...
    def goto_declaration(self, path: str, line: int, column: int) -> Any: ...
    def goto_type_definition(self, path: str, line: int, column: int) -> Any: ...
    def find_references(self, path: str, line: int, column: int, include_declaration: bool) -> Any: ...
    def semantic_tokens(
        self,
        path: str,
        *,
        start_line: int | None = None,
        start_col: int | None = None,
        end_line: int | None = None,
        end_col: int | None = None,
    ) -> Any: ...
    def file_occurrences(self, path: str) -> Any: ...
    def type_hierarchy(self, path: str, line: int, column: int) -> Any: ...
    def class_supertypes(self, path: str, line: int, column: int) -> Any: ...
    def hover(self, path: str, line: int, column: int) -> Any: ...
    def document_highlights(self, path: str, line: int, column: int) -> Any: ...
    def can_rename(self, path: str, line: int, column: int) -> Any: ...
    def rename(self, path: str, line: int, column: int, new_name: str) -> Any: ...
    def selection_ranges(self, path: str, line: int, column: int) -> Any: ...
    def folding_ranges(self, path: str) -> Any: ...
    def signature_help(self, path: str, line: int, column: int) -> Any: ...
    def completions(self, path: str, line: int, column: int, *, auto_import: bool = True) -> Any: ...
    def inlay_hints(self, path: str) -> Any: ...
    def hints(self, path: str) -> Any: ...
    def code_actions(
        self,
        path: str,
        start_line: int,
        start_col: int,
        end_line: int,
        end_col: int,
        diagnostic_id: str,
    ) -> Any: ...
