"""Type stub for the native Rust extension `tyo3._native_impl`.

The native module is compiled via PyO3/maturin and exports:
- ``TyProject`` — the main project handle (a pyclass)
- Exception types — Python-visible subclasses of PyRuntimeError

All return types are annotated as ``Any`` because the Rust layer returns
pythonize'd dicts that are validated into Pydantic models downstream.
"""

from typing import Any

class ProjectClosedError(RuntimeError): ...
class PathResolutionError(RuntimeError): ...
class PositionError(RuntimeError): ...
class AnalysisError(RuntimeError): ...

class TyProject:
    """A live handle to an open ty project database."""

    @staticmethod
    def open(root: str) -> TyProject: ...
    def reload(self) -> None: ...
    def close(self) -> None: ...
    def snapshot(self) -> TySnapshot: ...
    def files(self) -> list[str]: ...
    def check(self) -> Any: ...
    def check_file(self, path: str) -> Any: ...
    def document_symbols(self, path: str) -> Any: ...
    def workspace_symbols(self, query: str) -> Any: ...
    def goto_definition(self, path: str, line: int, column: int) -> Any: ...
    def goto_declaration(self, path: str, line: int, column: int) -> Any: ...
    def goto_type_definition(self, path: str, line: int, column: int) -> Any: ...
    def find_references(self, path: str, line: int, column: int, include_declaration: bool) -> Any: ...
    def semantic_tokens(self, path: str) -> Any: ...
    def file_occurrences(self, path: str) -> Any: ...
    def type_hierarchy(self, path: str, line: int, column: int) -> Any: ...
    def hover(self, path: str, line: int, column: int) -> Any: ...

class TySnapshot:
    """An immutable, revision-pinned read view of an open ty project database."""

    def check(self) -> Any: ...
    def close(self) -> None: ...
