"""Python wrapper around the Rust PyTyProject extension.

Wraps ``tyo3.TyProject`` (the PyO3 class) with Pydantic model validation.
Each method:

1. Calls the corresponding Rust method (which returns native PyO3 DTO objects)
2. Converts native objects to plain Python via :func:`_to_python`
3. Validates the result through Pydantic's ``model_validate``
4. Returns Pydantic-validated domain objects

Usage::

    from tyo3.rust_project import RustProject

    rp = RustProject("/path/to/project")
    files = rp.files()
    result = rp.check()

See RUST_BACKEND_IMPLEMENTATION.md §6.1 for the design.
"""

from __future__ import annotations

import warnings
from pathlib import Path as StdPath
from pathlib import PurePosixPath
from typing import Any

from tyo3.exceptions import (
    AnalysisError,
    InternalTyError,
    PathResolutionError,
    PositionError,
    ProjectClosedError,
    ProjectOpenError,
)
from tyo3.models.advanced import SemanticToken
from tyo3.models.analysis import CheckResult
from tyo3.models.navigation import (
    DefinitionTarget,
    HoverResult,
    NameOccurrence,
    Reference,
    TypeHierarchy,
)
from tyo3.models.symbols import Symbol

# The PyO3 extension module — must match
# #[pyo3(name = "_native_impl")] in rust/src/lib.rs
# The .so is placed inside the tyo3 Python package at src/tyo3/_native_impl.cpython-*.so
try:
    from tyo3 import _native_impl as _native
except ImportError:
    _native = None  # type: ignore[assignment]

# Import typed exception classes so we can catch Rust errors without string matching.
try:
    from tyo3._native_impl import (
        AnalysisError as _NativeAnalysisError,
    )
    from tyo3._native_impl import (
        PathResolutionError as _NativePathError,
    )
    from tyo3._native_impl import (
        PositionError as _NativePositionError,
    )
    from tyo3._native_impl import (
        ProjectClosedError as _NativeClosedError,
    )
except ImportError:
    # When the native extension isn't built, define dummy classes
    # that never match in `except` clauses.
    class _NativeClosedError(Exception):  # type: ignore[no-redef]
        pass

    class _NativePathError(Exception):  # type: ignore[no-redef]
        pass

    class _NativePositionError(Exception):  # type: ignore[no-redef]
        pass

    class _NativeAnalysisError(Exception):  # type: ignore[no-redef]
        pass


# ── Conversion helpers ────────────────────────────────────────────────────
# PyO3 enums (defined with #[pyclass(eq)]) are not Python str subclasses,
# so Pydantic StrEnum fields reject them.  PyO3 frozen structs lack
# __dict__, so Pydantic v2.13 from_attributes=True rejects them.
# We recursively convert the PyO3 object graph to plain Python types
# (dict, list, str) that Pydantic validates natively.


# Cache of known PyO3 enum types from the native extension.
# Populated from the Rust-side _TYO3_ENUM_TYPES module attribute.
_ENUM_TYPES: frozenset[type] = frozenset()
_ENUM_TYPES_BUILT: bool = False


def _build_enum_cache() -> None:
    """Cache the PyO3 enum types from the native extension module."""
    global _ENUM_TYPES, _ENUM_TYPES_BUILT
    if _ENUM_TYPES_BUILT or _native is None:
        return
    enum_list = getattr(_native, "_TYO3_ENUM_TYPES", None)
    if enum_list is not None:
        _ENUM_TYPES = frozenset(enum_list)
    else:
        import logging
        logging.getLogger(__name__).warning(
            "_TYO3_ENUM_TYPES not found on native module. "
            "Enum detection will not work. Rebuild the Rust extension."
        )
        _ENUM_TYPES = frozenset()
    _ENUM_TYPES_BUILT = True


def _is_native_enum(obj: Any) -> bool:
    """Return True if *obj* is a PyO3 native enum variant."""
    _build_enum_cache()
    return type(obj) in _ENUM_TYPES


# Tags that need no conversion
_PASSTHROUGH_TAGS = frozenset({"str", "int", "float", "bool"})


def _to_python(obj: Any) -> Any:
    """Recursively convert PyO3 native objects to plain Python types.

    Uses ``__fields__`` classattrs (generated by ``#[derive(PyFields)]``)
    for struct conversion and ``_TYO3_ENUM_TYPES`` for enum detection.
    Type tags on fields allow skipping recursion for primitives.

    Type tag semantics:
        "str", "int", "float", "bool" → passthrough (no recursion)
        "obj"                         → full recursive _to_python()
        "opt:<tag>"                   → None passthrough, else convert by <tag>
        "list:<tag>"                  → convert each element by <tag>
    """
    if obj is None or isinstance(obj, (bool, int, float, str)):
        return obj

    if isinstance(obj, (list, tuple)):
        return [_to_python(item) for item in obj]

    if _is_native_enum(obj):
        return str(obj)

    # PyO3 frozen struct with __fields__ classattr
    fields = getattr(type(obj), "__fields__", None)
    if fields is not None:
        return _convert_struct(obj, fields)

    # Fallback for structs without __fields__ — logs a warning so new
    # unregistered types are caught during development.
    import logging
    logging.getLogger(__name__).warning(
        "Unknown native type %s — falling back to dir() introspection. "
        "Add #[derive(PyFields)] to the Rust struct.",
        type(obj).__name__,
    )
    return _convert_struct_fallback(obj)


def _convert_struct(obj: Any, fields: list[tuple[str, str]]) -> dict[str, Any]:
    """Convert a PyO3 struct using its __fields__ metadata."""
    result: dict[str, Any] = {}
    for name, tag in fields:
        val = getattr(obj, name)
        result[name] = _convert_by_tag(val, tag)
    return result


def _convert_by_tag(val: Any, tag: str) -> Any:
    """Convert a value according to its type tag."""
    if tag in _PASSTHROUGH_TAGS:
        return val

    if tag.startswith("opt:"):
        if val is None:
            return None
        return _convert_by_tag(val, tag[4:])

    if tag.startswith("list:"):
        inner_tag = tag[5:]
        if inner_tag in _PASSTHROUGH_TAGS:
            return list(val) if not isinstance(val, list) else val
        return [_convert_by_tag(item, inner_tag) for item in val]

    # "obj" — full recursive conversion (struct or enum)
    return _to_python(val)


def _convert_struct_fallback(obj: Any) -> dict[str, Any]:
    """Legacy fallback for structs without __fields__."""
    result: dict[str, Any] = {}
    for name in dir(obj):
        if name.startswith("_"):
            continue
        try:
            val = getattr(obj, name)
            if not callable(val):
                result[name] = _to_python(val)
        except Exception:
            pass
    return result


# ── RustProject ─────────────────────────────────────────────────────────────


class RustProject:
    """Wraps the Rust :class:`TyProject` for Pydantic-validated access.

    Owns an internal handle to the ``ProjectDatabase`` via the PyO3 boundary.
    """

    def __init__(self, root: str | StdPath) -> None:
        if _native is None:
            raise ProjectOpenError(
                "Rust native extension is not built. Run `maturin develop` inside the devenv shell first."
            )
        root_str = str(root)
        try:
            self._inner = _native.TyProject.open(root_str)
        except Exception as e:
            raise ProjectOpenError(f"Cannot open project at '{root_str}': {e}") from e
        self._root = StdPath(root_str).resolve()
        self._closed = False

    @property
    def root(self) -> StdPath:
        return self._root

    # ── Guard ──────────────────────────────────────────────────────

    def _check_open(self) -> None:
        """Raise ProjectClosedError if this project has been closed."""
        if self._closed:
            raise ProjectClosedError("Project is closed")

    # ── Files ────────────────────────────────────────────────────────

    def files(self) -> list[PurePosixPath]:
        """Return the file paths known to this project."""
        self._check_open()
        try:
            raw: list[str] = self._inner.files()
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in files(): {e}") from e
        return [PurePosixPath(p) for p in raw]

    # ── Check ────────────────────────────────────────────────────────

    def check(self) -> CheckResult:
        """Run the type-checker and return structured diagnostics."""
        self._check_open()
        try:
            native_result = self._inner.check()
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativeAnalysisError as e:
            raise AnalysisError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in check(): {e}") from e

        return CheckResult.model_validate(_to_python(native_result))

    def check_file(self, path: str | StdPath) -> CheckResult:
        """Run the type-checker and return diagnostics for a single file."""
        self._check_open()
        try:
            native_result = self._inner.check_file(str(path))
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePathError as e:
            raise PathResolutionError(str(e)) from e
        except _NativeAnalysisError as e:
            raise AnalysisError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in check_file(): {e}") from e

        return CheckResult.model_validate(_to_python(native_result))

    # ── Document Symbols ─────────────────────────────────────────────

    def document_symbols(self, path: str | StdPath) -> list[Symbol]:
        """Return symbols defined in the given file."""
        self._check_open()
        try:
            native_symbols = self._inner.document_symbols(str(path))
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePathError as e:
            raise PathResolutionError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in document_symbols(): {e}") from e

        return [Symbol.model_validate(_to_python(s)) for s in native_symbols]

    # ── Workspace Symbols ────────────────────────────────────────────

    def workspace_symbols(self, query: str) -> list[Symbol]:
        """Search for symbols matching *query* across the project."""
        if not query:
            return []
        self._check_open()
        try:
            native_symbols = self._inner.workspace_symbols(query)
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in workspace_symbols(): {e}") from e

        return [Symbol.model_validate(_to_python(s)) for s in native_symbols]

    # ── Goto Definition ──────────────────────────────────────────────

    def goto_definition(self, path: str | StdPath, line: int, column: int) -> list[DefinitionTarget]:
        """Navigate to the definition of the symbol at *(line, column)*."""
        return self._goto("goto_definition", path, line, column)

    # ── Goto Declaration ─────────────────────────────────────────────

    def goto_declaration(self, path: str | StdPath, line: int, column: int) -> list[DefinitionTarget]:
        """Navigate to the declaration of the symbol at *(line, column)*."""
        return self._goto("goto_declaration", path, line, column)

    # ── Goto Type Definition ─────────────────────────────────────────

    def goto_type_definition(self, path: str | StdPath, line: int, column: int) -> list[DefinitionTarget]:
        """Navigate to the type definition of the symbol at *(line, column)*."""
        return self._goto("goto_type_definition", path, line, column)

    def _goto(self, method: str, path: str | StdPath, line: int, column: int) -> list[DefinitionTarget]:
        """Shared implementation for all goto-* methods."""
        self._check_open()
        try:
            native_targets = getattr(self._inner, method)(str(path), line, column)
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePositionError as e:
            raise PositionError(str(e)) from e
        except _NativePathError as e:
            raise PathResolutionError(str(e)) from e
        except OverflowError as e:
            raise PositionError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in {method}(): {e}") from e

        return [DefinitionTarget.model_validate(_to_python(t)) for t in native_targets]

    # ── Find References ─────────────────────────────────────────────

    def find_references(
        self,
        path: str | StdPath,
        line: int,
        column: int,
        include_declaration: bool = True,
    ) -> list[Reference]:
        """Find all references to the symbol at *(line, column)*."""
        self._check_open()
        try:
            native_refs = self._inner.find_references(str(path), line, column, include_declaration)
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePositionError as e:
            raise PositionError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in find_references(): {e}") from e

        return [Reference.model_validate(_to_python(r)) for r in native_refs]

    # ── Semantic Tokens ──────────────────────────────────────────

    def semantic_tokens(self, path: str | StdPath) -> list[SemanticToken]:
        """Return semantic tokens for a file."""
        self._check_open()
        try:
            native_result = self._inner.semantic_tokens(str(path))
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePathError as e:
            raise PathResolutionError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in semantic_tokens(): {e}") from e

        path_posix = PurePosixPath(str(path))
        result = []
        for t in native_result:
            d = _to_python(t)
            d["file"] = path_posix
            result.append(SemanticToken.model_validate(d))
        return result

    # ── File Occurrences ─────────────────────────────────────────

    def file_occurrences(self, path: str | StdPath) -> list[NameOccurrence]:
        """Batch-resolve all name occurrences in a file.

        Returns every name-like token in the file, each resolved to
        its definition target and classified by reference role.

        This replaces per-token ``goto_definition`` calls with a single
        Rust call — O(1) FFI calls instead of O(tokens).
        """
        self._check_open()
        try:
            native_result = self._inner.file_occurrences(str(path))
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePathError as e:
            raise PathResolutionError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in file_occurrences(): {e}") from e

        return [NameOccurrence.model_validate(_to_python(o)) for o in native_result]

    # ── Hover ────────────────────────────────────────────────────────

    def hover(self, path: str | StdPath, line: int, column: int) -> HoverResult | None:
        """Get hover information for the symbol at *(line, column)*.

        Returns ``None`` when no hover information is available.
        """
        self._check_open()
        try:
            native_hover = self._inner.hover(str(path), line, column)
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePositionError as e:
            raise PositionError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in hover(): {e}") from e

        if native_hover is None:
            return None

        return HoverResult.model_validate(_to_python(native_hover))

    # ── Type Hierarchy ───────────────────────────────────────────

    def type_hierarchy(
        self, path: str | StdPath, line: int, column: int
    ) -> TypeHierarchy | None:
        """Query type hierarchy at a position."""
        self._check_open()
        try:
            native_result = self._inner.type_hierarchy(str(path), line, column)
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except _NativePathError as e:
            raise PathResolutionError(str(e)) from e
        except _NativePositionError as e:
            raise PositionError(str(e)) from e
        except OverflowError as e:
            raise PositionError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in type_hierarchy(): {e}") from e

        if native_result is None:
            return None
        return TypeHierarchy.model_validate(_to_python(native_result))

    # ── Lifecycle ────────────────────────────────────────────────────

    def reload(self) -> None:
        """Reload the project, clearing cached diagnostics and re-scanning."""
        self._check_open()
        try:
            self._inner.reload()
        except _NativeClosedError as e:
            raise ProjectClosedError(str(e)) from e
        except Exception as e:
            raise InternalTyError(f"Unexpected error in reload(): {e}") from e

    def close(self) -> None:
        """Close the project and free Rust-side resources.

        Safe to call multiple times — subsequent calls are no-ops.
        """
        if self._closed:
            return
        self._inner.close()
        self._closed = True

    def __enter__(self) -> RustProject:
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        self.close()

    def __del__(self) -> None:
        # Guard against interpreter shutdown — if the native module is already
        # unloaded, self._inner will be None and we must not call into Rust.
        if getattr(self, "_inner", None) is None:
            return
        if not getattr(self, "_closed", True):
            warnings.warn(
                "RustProject was not closed explicitly. "
                "Use 'with RustProject(...) as rp:' or call rp.close().",
                ResourceWarning,
                stacklevel=2,
            )
            try:
                self.close()
            except Exception:
                pass
